### PR TITLE
Support redirect on http_request resource (close #187)

### LINKED ISSUE #187: Support redirect on http_request resource
Supporting redirect on `http_request` resource is required?
Like this.

```ruby
uri = URI.parse(attributes.url)
retry_count = 5
retry_count.times do
  http = Net::HTTP.new(uri.host, uri.port)
  response = http.method(attributes.action).call(uri.request_uri, attributes.headers)

  case response
  when Net::HTTPRedirection
    url = URI.parse(response['Location'])
    next
  else
    break
  end
end
```

### PR DESCRIPTION
**Pull request by hico-horiuchi**
Happy new year :tada:
This is implementation of #187 based on [chef/chef/lib/chef/http.rb](https://github.com/chef/chef/blob/master/lib/chef/http.rb#L363#L371).

For example: 

```ruby
http_request "/tmp/http_request_redirect.html" do
  redirect_limit 1
  url "https://httpbin.org/redirect-to?url=https%3A%2F%2Fhttpbin.org%2Fget%3Ffrom%3Ditamae"
end
```

### CODE REVIEW

**Comment by hico-horiuchi** [comment]
@ryotarai The following errors are occured at wercker.
Would you check this problem?

```
 INFO :       package[dstat] installed will change from 'false' to 'true'
DEBUG :       Executing `dpkg-query -f '${Status}' -W dstat | grep -E '^(install|hold) ok installed$'`...
DEBUG :         stdout | dpkg-query: no packages found matching dstat
DEBUG :         exited with 1
DEBUG :       Executing `DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold'  install dstat`...
DEBUG :         stdout | Reading package lists... 0%Reading package lists... 100%Reading package lists... Done
DEBUG :         stdout | Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
DEBUG :         stdout | Reading state information... 0%Reading state information... 1%Reading state information... Done
DEBUG :         stdout | The following packages were automatically installed and are no longer required:
DEBUG :         stdout |   linux-headers-3.13.0-57 linux-headers-3.13.0-57-generic
DEBUG :         stdout |   linux-headers-3.13.0-61 linux-headers-3.13.0-61-generic
DEBUG :         stdout |   linux-image-3.13.0-57-generic linux-image-3.13.0-61-generic
DEBUG :         stdout |   linux-image-extra-3.13.0-57-generic linux-image-extra-3.13.0-61-generic
DEBUG :         stdout | Use 'apt-get autoremove' to remove them.
DEBUG :         stdout | The following NEW packages will be installed:
DEBUG :         stdout |   dstat
DEBUG :         stdout | 0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
DEBUG :         stdout | Need to get 68.2 kB of archives.
DEBUG :         stdout | After this operation, 351 kB of additional disk space will be used.
DEBUG :         stdout | WARNING: The following packages cannot be authenticated!
DEBUG :         stdout |   dstat
DEBUG :         stdout | E: There are problems and -y was used without --force-yes
ERROR :         Command `DEBIAN_FRONTEND='noninteractive' apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold'  install dstat` failed. (exit status: 100)
ERROR :   package[dstat] Failed.
```

**Comment by hico-horiuchi** [comment]
Sorry, I amend the commit and force-pushed to retry tests.

**Comment by ryotarai** [comment]
Thank you!

**Comment by ryotarai** [comment]
released in v1.9.3

**Pull request merged**
