### PR TITLE
add support of FreeBSD Jail

### PR DESCRIPTION
**Pull request by yuichiro-naito**
I reopened https://github.com/itamae-kitchen/itamae/pull/245 .
This pull request has only one fix which adds support of FreeBSD Jail.
Following message is my original pull request.

I wrote a patch that makes Itamae to support FreeBSD jail (*1).
I tested all Itamae resources work with Specinfra-2.70.1.

My fix is quite simple.

 -   added jexec backend which executes specinfra commands in jail.
 -   added Itamae jail subcommand.

Here is a example to use Itamae jail subcommand.

```
$ su
# itamae jail --jail_name <jail_name> <recipe> ...
```

Itamae jail subcommand requires root privilege,
because FreeBSD's jexec command requires root privilege.

Will you see my fixes and merge this Pull Request?

*1: FreeBSD jail information
https://www.freebsd.org/doc/handbook/jails.html
https://ja.wikipedia.org/wiki/FreeBSD_jail

### CODE REVIEW

**Comment by yuichiro-naito** [comment]
Over one month has passed since I created this Pull Request.
Are there any issues about stopping development?

**Comment by yuichiro-naito** [comment]
I want to use this feature on FreeBSD.
Please merge and release new version.

**Comment by sue445** [comment]
@yuichiro-naito Sorry for late reply.

I think this is LGTM, but CI is broken at your branch. Please `rebase` (or `merge` ) latest master.

**Comment by yuichiro-naito** [comment]
I have merged master branch.
All tests are passed successfully.

**Comment by sue445** [comment]
@yuichiro-naito `v1.9.12` is released :gem:

**Pull request merged**
