### PR TITLE
Add Option. docker_container_create_options

### PR DESCRIPTION
**Pull request by umisora**
# About
You can set docker_container_create_options to config.yaml.

# Usecase
`docker_container_create_options` 
I want to set hostname to container when exec itamae.
My Itamae-Recipes has Case Statement by host name.

Is this option will merge, I will be able to set hostname to container.. 

# options
Do not prepare option that can be passed as arguments.
You can set option to `config.yaml` when using `--config` arguments.

example)

itamae.config.yaml
```
docker_container_create_options:
  name: itamae-docker
  Hostname: itamae-docker
  Domainname: localhost.com
```

### CODE REVIEW

**Comment by ryotarai** [comment]
```
  Hostname: itamae-docker
  Domainname: localhost.com
```

These capitalized keys are not comfortable for me in terms of consistency.

**Comment by umisora** [comment]
[Docker API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/tag-an-image-into-a-repository%23create-a-container) reference uses camelcase strings. So I wrote example `itamae.config.yaml` with camelcase strings.

Do you think it is better to insert some components to translate `itamae.config.yaml` to fit with API's standard formats (in this case to translate to camelcase strings) ?

Do you agree to make it possible to set the hostname with the option of [docker_container_create_options]?

**Comment by umisora** [comment]
and more...
Even If you use Lower case in `itamae.config.yaml`,  it works.

**Comment by umisora** [comment]
|ω・`） @ryotarai

**Comment by ryotarai** [comment]
> Even If you use Lower case in itamae.config.yaml, it works

Okay, I gonna merge this.

**Comment by umisora** [comment]
Thank you !

**Comment by ryotarai** [comment]
released in v1.9.11

**Pull request merged**
