### PR TITLE
add mysql resource

### PR DESCRIPTION
**Pull request by letusfly85**
I added mysql resource for itamae.

It enables to create database, user by using itamae.

### CODE REVIEW

**Comment by ryotarai** [comment]
Thank you for your pull request.
mysql resource is good idea but it is not necessary for everyone and it adds new dependency (mysql2 which requires mysql libraries) to Itamae.
So I can't merge this but you can create a gem as [resource plugin](https://github.com/itamae-kitchen/itamae/wiki/Resource-Plugins)

**Comment by letusfly85** [comment]
I see, thank you!

**Comment by letusfly85** [comment]
done

https://github.com/letusfly85/itamae-plugin-resource-mysql

**Comment by ryotarai** [comment]
Good. In my opinion, `mysql_user` resource is better than `mysql`.

**Comment by letusfly85** [comment]
Thanks!

done

https://github.com/letusfly85/itamae-plugin-resource-mysql_user

**Pull request closed without merging**
