### PR TITLE
Improve `file` resource performance

### PR DESCRIPTION
**Pull request by labocho**
Now, `Itamae::Resource::File#pre_action` always transfer file content. But when the file is not modified, it is not necessary and spends time.

In this pull request, if the file exists on remote and `sha256sum` command is available, compare digest and avoid unnecessary file transfer.

30%+ faster in the benchmark below.
https://gist.github.com/labocho/23f8e089205a507e6089ce1e8ce5a863

### CODE REVIEW

**Comment by unasuke** [comment]
@labocho Could you squash those commits?

**Comment by labocho** [comment]
@unasuke Yes! Done.

**Comment by sue445** [comment]
I released as `v1.10.7` 💎

**Comment by labocho** [comment]
Thanks!

**Pull request merged**
