### PR TITLE
Support `only_if` and `not_if` inside a `define`

### LINKED ISSUE #161: `not_if` / `only_if` don't work inside a `define`
If the `not_if`/`only_if` directives could be applied to all resources
contained within a `define`, it would help to DRY up my code.. right now I'm
using a workaround like this:

``` ruby
define :bootstrap_install do
  test_cmd = "dpkg-query -Wf'${db:Status-abbrev}' #{params[:name]} | grep '^i'"
  installed = run_command(test_cmd, error: false).exit_status == 0

  # run install if required
  (params[:name], params[:dependencies]).map do |pkg|
    "/tmp/#{pkg}_amd64.deb"
  end.each do |path|
    remote_file path do
      not_if installed
    end
    execute "dpkg -i #{path}" do
      not_if installed
    end
    file path do
      action :delete
      not_if installed
    end
  end
end
```

Whereas I'd like to be able to do:

``` ruby
define :bootstrap_install do
  not_if "dpkg-query -Wf'${db:Status-abbrev}' #{params[:name]} | grep '^i'"

  (params[:name], params[:dependencies]).map do |pkg|
    "/tmp/#{pkg}_amd64.deb"
  end.each do |path|
    remote_file path
    execute "dpkg -i #{path}"
    file path do
      action :delete
    end
  end
end
```

### LINKED ISSUE #262: Support only_if and not_if to definition
# Example
```ruby
define :some_definition do
end

some_definition do
  only_if "xxxxx"
  # or
  not_if "xxxxx"
end
```

related #161

### PR DESCRIPTION
**Pull request by sue445**
c.f. #262

# Example
```ruby
define :some_definition do
end

# this is executed
some_definition do
  only_if "exit 0"
end

# this is not executed
some_definition do
  only_if "exit 1"
end
```

Close #262 
Close #161

### CODE REVIEW

**Comment by sue445** [comment]
@unasuke I removed WIP. Please review this 🙇

**Comment by ryotarai** [comment]
This implementation evaluates `only_if` and `not_if` in the phase of loading recipes but `only_if` and `not_if` of normal resources (!= definition) are evaluated in the running phase.
For instance, in this recipe, `echo` is not executed:

```ruby
execute 'touch /tmp/a'

define :echo do
  execute 'echo B'
end

execute 'echo A' do
  only_if 'test -f /tmp/a'
end

echo 'echo' do
  only_if 'test -f /tmp/a'
end
```

```
 INFO : Starting Itamae...
 INFO : Recipe: /Users/ryotarai/src/github.com/itamae-kitchen/itamae/tmp/a.rb
 INFO :   execute[touch /tmp/a] executed will change from 'false' to 'true'
 INFO :   execute[echo A] executed will change from 'false' to 'true'
```

**Comment by sue445** [comment]
@ryotarai oops... I'll fix this.

**Comment by sue445** [comment]
@ryotarai @unasuke I fixed this problem. Please review again 🙇 

log that executed  https://github.com/itamae-kitchen/itamae/pull/271#issuecomment-433775262

```
$ be ./bin/itamae local /tmp/test.rb
 INFO : Starting Itamae...
 INFO : Recipe: /tmp/test.rb
 INFO :   execute[touch /tmp/a] executed will change from 'false' to 'true'
 INFO :   execute[echo A] executed will change from 'false' to 'true'
 INFO :     execute[echo B] executed will change from 'false' to 'true'
```

**Comment by unasuke** [comment]
:eyes: 

https://travis-ci.org/itamae-kitchen/itamae/jobs/450251581#L4897

**Pull request merged**
